import type { Product } from "@/hooks/useProducts";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "seed-01",
    name: "Maasai Shuka Wrap",
    price: 2500,
    imageDataUrl: "https://picsum.photos/seed/swe-shuka/400/500",
    category: "Clothing",
    likes: 18,
    likedBy: [],
    comments: [
      { id: "c1", userId: "u1", username: "Wanjiku", text: "Beautiful! Where can I get this?", timestamp: "2026-03-20T10:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "seed-02",
    name: "Ankara Print Dress",
    price: 3800,
    imageDataUrl: "https://picsum.photos/seed/swe-ankara/400/500",
    category: "Clothing",
    likes: 31,
    likedBy: [],
    comments: [
      { id: "c2", userId: "u2", username: "Amina", text: "Stunning colours, I love it!", timestamp: "2026-03-21T14:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 19).toISOString(),
  },
  {
    id: "seed-03",
    name: "Kitenge Shirt (Men's)",
    price: 1800,
    imageDataUrl: "https://picsum.photos/seed/swe-kitenge/400/500",
    category: "Clothing",
    likes: 12,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
  },
  {
    id: "seed-04",
    name: "Hand-Beaded Maasai Necklace",
    price: 1200,
    imageDataUrl: "https://picsum.photos/seed/swe-bead/400/500",
    category: "Jewelry",
    likes: 27,
    likedBy: [],
    comments: [
      { id: "c4", userId: "u3", username: "Fatuma", text: "Gorgeous craftsmanship!", timestamp: "2026-03-22T09:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 17).toISOString(),
  },
  {
    id: "seed-05",
    name: "Kanga Fabric Roll (2m)",
    price: 900,
    imageDataUrl: "https://picsum.photos/seed/swe-kanga/400/500",
    category: "Fabric",
    likes: 9,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 16).toISOString(),
  },
  {
    id: "seed-06",
    name: "Leather Kiondo Basket Bag",
    price: 3500,
    imageDataUrl: "https://picsum.photos/seed/swe-kiondo/400/500",
    category: "Accessories",
    likes: 44,
    likedBy: [],
    comments: [
      { id: "c6", userId: "u4", username: "Grace", text: "Ordered mine yesterday!", timestamp: "2026-03-23T11:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "seed-07",
    name: "Dashiki Print Top",
    price: 1500,
    imageDataUrl: "https://picsum.photos/seed/swe-dashiki/400/500",
    category: "Clothing",
    likes: 16,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: "seed-08",
    name: "Woven Sisal Handbag",
    price: 2200,
    imageDataUrl: "https://picsum.photos/seed/swe-sisal/400/500",
    category: "Accessories",
    likes: 20,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 13).toISOString(),
  },
  {
    id: "seed-09",
    name: "Ankara Wrap Skirt",
    price: 2800,
    imageDataUrl: "https://picsum.photos/seed/swe-wrapskirt/400/500",
    category: "Clothing",
    likes: 35,
    likedBy: [],
    comments: [
      { id: "c9", userId: "u5", username: "Mercy", text: "Perfect for Sunday best!", timestamp: "2026-03-24T08:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: "seed-10",
    name: "Kikoy Beach Wrap",
    price: 1100,
    imageDataUrl: "https://picsum.photos/seed/swe-kikoy/400/500",
    category: "Clothing",
    likes: 23,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
  },
  {
    id: "seed-11",
    name: "Indigo Batik Jacket",
    price: 5500,
    imageDataUrl: "https://picsum.photos/seed/swe-batik/400/500",
    category: "Clothing",
    likes: 52,
    likedBy: [],
    comments: [
      { id: "c11", userId: "u6", username: "Sharon", text: "This is everything!", timestamp: "2026-03-25T16:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "seed-12",
    name: "Bone & Bead Bracelet Set",
    price: 750,
    imageDataUrl: "https://picsum.photos/seed/swe-bone/400/500",
    category: "Jewelry",
    likes: 11,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "seed-13",
    name: "Nairobi Streetwear Hoodie",
    price: 2900,
    imageDataUrl: "https://picsum.photos/seed/swe-hoodie/400/500",
    category: "Clothing",
    likes: 38,
    likedBy: [],
    comments: [
      { id: "c13", userId: "u7", username: "Brian", text: "Rep Nairobi!", timestamp: "2026-03-26T12:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "seed-14",
    name: "East African Earrings Set",
    price: 950,
    imageDataUrl: "https://picsum.photos/seed/swe-earring/400/500",
    category: "Jewelry",
    likes: 19,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "seed-15",
    name: "Kitenge Co-ord Set",
    price: 4200,
    imageDataUrl: "https://picsum.photos/seed/swe-coord/400/500",
    category: "Clothing",
    likes: 61,
    likedBy: [],
    comments: [
      { id: "c15", userId: "u8", username: "Lilian", text: "I need this in my life!", timestamp: "2026-03-27T09:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "seed-16",
    name: "Kikuyu Woven Blanket",
    price: 3100,
    imageDataUrl: "https://picsum.photos/seed/swe-blanket/400/500",
    category: "Fabric",
    likes: 7,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "seed-17",
    name: "Wicker Wide-Brim Sun Hat",
    price: 1400,
    imageDataUrl: "https://picsum.photos/seed/swe-hat/400/500",
    category: "Accessories",
    likes: 14,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "seed-18",
    name: "Embroidered Kaftan Dress",
    price: 6800,
    imageDataUrl: "https://picsum.photos/seed/swe-kaftan/400/500",
    category: "Clothing",
    likes: 47,
    likedBy: [],
    comments: [
      { id: "c18", userId: "u9", username: "Naomi", text: "Absolute royalty vibes!", timestamp: "2026-03-28T10:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "seed-19",
    name: "Hand-Beaded Leather Belt",
    price: 1750,
    imageDataUrl: "https://picsum.photos/seed/swe-belt/400/500",
    category: "Accessories",
    likes: 29,
    likedBy: [],
    comments: [],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "seed-20",
    name: "Maasai Leather Sandals",
    price: 2200,
    imageDataUrl: "https://picsum.photos/seed/swe-sandal/400/500",
    category: "Footwear",
    likes: 33,
    likedBy: [],
    comments: [
      { id: "c20", userId: "u10", username: "Kevin", text: "Durable and stylish, great combo!", timestamp: "2026-03-29T07:00:00Z" },
    ],
    ownerId: "system",
    ownerName: "Elizabeth",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];
