import type { Product } from "@workspace/api-client-react";

export const SEED_PRODUCTS: Product[] = [
  { id: "seed-01", name: "Maasai Shuka Wrap", description: "Traditional red tartan shuka made from soft acrylic blend. Perfect for cultural events or everyday wrap-style wear.", price: 2500, imageUrl: "https://picsum.photos/seed/swe-shuka/400/500", category: "Clothing", likesCount: 18, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 20).toISOString() },
  { id: "seed-02", name: "Ankara Print Dress", description: "Vibrant African print midi dress with fitted bodice and flared skirt. Size M, 100% cotton wax print fabric.", price: 3800, imageUrl: "https://picsum.photos/seed/swe-ankara/400/500", category: "Clothing", likesCount: 31, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 19).toISOString() },
  { id: "seed-03", name: "Kitenge Shirt (Men's)", description: "Short-sleeved button-up shirt in bold kitenge print. Lightweight cotton, tailored fit, size L.", price: 1800, imageUrl: "https://picsum.photos/seed/swe-kitenge/400/500", category: "Clothing", likesCount: 12, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 18).toISOString() },
  { id: "seed-04", name: "Hand-Beaded Maasai Necklace", description: "Authentic beaded necklace handcrafted by Maasai artisans. Colorful glass beads in traditional pattern.", price: 1200, imageUrl: "https://picsum.photos/seed/swe-bead/400/500", category: "Jewelry", likesCount: 27, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 17).toISOString() },
  { id: "seed-05", name: "Kanga Fabric Roll (2m)", description: "Pure cotton kanga with Swahili proverb border print. 2-meter length, ideal for wraps or home decor.", price: 900, imageUrl: "https://picsum.photos/seed/swe-kanga/400/500", category: "Fabric", likesCount: 9, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 16).toISOString() },
  { id: "seed-06", name: "Leather Kiondo Basket Bag", description: "Handwoven sisal basket with genuine leather trim and handles. Medium size, perfect everyday tote.", price: 3500, imageUrl: "https://picsum.photos/seed/swe-kiondo/400/500", category: "Accessories", likesCount: 44, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 15).toISOString() },
  { id: "seed-07", name: "Dashiki Print Top", description: "Loose-fit dashiki tunic with embroidered neckline. Unisex style, breathable cotton, one size fits most.", price: 1500, imageUrl: "https://picsum.photos/seed/swe-dashiki/400/500", category: "Clothing", likesCount: 16, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 14).toISOString() },
  { id: "seed-08", name: "Woven Sisal Handbag", description: "Natural sisal shoulder bag with colorful woven patterns. Eco-friendly and durable, great for daily use.", price: 2200, imageUrl: "https://picsum.photos/seed/swe-sisal/400/500", category: "Accessories", likesCount: 20, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 13).toISOString() },
  { id: "seed-09", name: "Ankara Wrap Skirt", description: "High-waist wrap skirt in bold ankara wax print. Adjustable tie, knee-length, fits sizes 8-12.", price: 2800, imageUrl: "https://picsum.photos/seed/swe-wrapskirt/400/500", category: "Clothing", likesCount: 35, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 12).toISOString() },
  { id: "seed-10", name: "Kikoy Beach Wrap", description: "Lightweight cotton kikoy in classic stripe pattern. Multi-use wrap, beach towel, or sarong.", price: 1100, imageUrl: "https://picsum.photos/seed/swe-kikoy/400/500", category: "Clothing", likesCount: 23, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 11).toISOString() },
  { id: "seed-11", name: "Indigo Batik Jacket", description: "Hand-dyed indigo batik denim jacket with unique wax-resist patterns. Limited edition, size M.", price: 5500, imageUrl: "https://picsum.photos/seed/swe-batik/400/500", category: "Clothing", likesCount: 52, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 10).toISOString() },
  { id: "seed-12", name: "Bone & Bead Bracelet Set", description: "Handmade bracelet trio with natural bone, wood, and glass beads. Adjustable cord, unisex design.", price: 750, imageUrl: "https://picsum.photos/seed/swe-bone/400/500", category: "Jewelry", likesCount: 11, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 9).toISOString() },
  { id: "seed-13", name: "Nairobi Streetwear Hoodie", description: "Urban streetwear hoodie with Nairobi skyline print. Heavy cotton fleece, kangaroo pocket, size L.", price: 2900, imageUrl: "https://picsum.photos/seed/swe-hoodie/400/500", category: "Clothing", likesCount: 38, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 8).toISOString() },
  { id: "seed-14", name: "East African Earrings Set", description: "Geometric brass earrings with colorful beadwork. Lightweight dangle style, nickel-free hooks.", price: 950, imageUrl: "https://picsum.photos/seed/swe-earring/400/500", category: "Jewelry", likesCount: 19, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 7).toISOString() },
  { id: "seed-15", name: "Kitenge Co-ord Set", description: "Matching crop top and palazzo pants in vibrant kitenge print. Cotton blend, size M, perfect for summer.", price: 4200, imageUrl: "https://picsum.photos/seed/swe-coord/400/500", category: "Clothing", likesCount: 61, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 6).toISOString() },
  { id: "seed-16", name: "Kikuyu Woven Blanket", description: "Thick wool-blend blanket in traditional Kikuyu weave pattern. Warm and durable, 150x200cm.", price: 3100, imageUrl: "https://picsum.photos/seed/swe-blanket/400/500", category: "Fabric", likesCount: 7, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: "seed-17", name: "Wicker Wide-Brim Sun Hat", description: "Natural woven straw hat with wide brim for sun protection. Adjustable inner band, lightweight and breathable.", price: 1400, imageUrl: "https://picsum.photos/seed/swe-hat/400/500", category: "Accessories", likesCount: 14, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 4).toISOString() },
  { id: "seed-18", name: "Embroidered Kaftan Dress", description: "Luxe floor-length kaftan with intricate gold thread embroidery. Silk-cotton blend, one size, elegant occasion wear.", price: 6800, imageUrl: "https://picsum.photos/seed/swe-kaftan/400/500", category: "Clothing", likesCount: 47, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: "seed-19", name: "Hand-Beaded Leather Belt", description: "Genuine leather belt with Maasai beadwork detail. Adjustable buckle, fits waist 28-34 inches.", price: 1750, imageUrl: "https://picsum.photos/seed/swe-belt/400/500", category: "Accessories", likesCount: 29, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: "seed-20", name: "Maasai Leather Sandals", description: "Handcrafted leather sandals with traditional tire-sole base. Comfortable fit, sizes 38-42 available.", price: 2200, imageUrl: "https://picsum.photos/seed/swe-sandal/400/500", category: "Footwear", likesCount: 33, userLiked: false, comments: [], ownerId: "system", ownerName: "Elizabeth", createdAt: new Date(Date.now() - 86400000 * 1).toISOString() },
];
